### ISSUE TITLE
Great project! Looking forward to examples for transaction history

### ISSUE THREAD

**Issue by chiggimps** [0xOmarA/RadixLib#1]
I know you just started this. Been looking for a python wrapper so thank you. How do I run?

Obviously, this is not the way ...
```
from provider import Provider
Provider().get_transaction_history(
    address="rdx1...",
    size=1000
)
```

**Comment by 0xOmarA** [comment]
Hey man, I just saw this. Here is a working example which showcases how you can get the transaction history for a given address: 

```py
import Radix

# Creating the provider object which will be talking to the blockchain
provider: Radix.Provider = Radix.Provider(Radix.Network.STOKENET)

# Getting the transaction history for a given address
history: dict = provider.get_transaction_history(
    address = 'tdx1qspqqecwh3tgsgz92l4d4f0e4egmfe86049dj75pgq347fkkfmg84pgx9um0v', 
    size = 100
).json()

print(history['result'])
```

In this case, I'm connecting my provider to the Stokenet and not to the mainnet and I'm asking the provider to get me the transaction history for the stokenet address `tdx1qspqqecwh3tgsgz92l4d4f0e4egmfe86049dj75pgq347fkkfmg84pgx9um0v`.

You can modify the above code to run on the mainnet by doing the following: 

```py
import Radix

# Creating the provider object which will be talking to the blockchain
provider: Radix.Provider = Radix.Provider(Radix.Network.MAINNET)

# Getting the transaction history for a given address
history: dict = provider.get_transaction_history(
    address = 'rdx1...', 
    size = 100
).json()

print(history['result'])
```

Let me know if you need any additional help and I'd be glad to help :)

**Edit:** The above code is from an older version of this package back when the archive node was still in use. If you would like to see an example on how to get the transaction history for an account please checkout the example [here](https://github.com/0xOmarA/RadixLib/blob/master/examples/9-%20getting%20transaction%20history/method%201.py)
