### ISSUE TITLE
Way to decode the message_blob in transactions that supports new and legacy message

### ISSUE THREAD

**Issue by chiggimps** [0xOmarA/RadixLib#3]
This Gist, decode_radix_message_with_legacy_support.py, is intended to be pseudocode. Is there a way you could formalize this and include message decoding in this wonderful library?

https://gist.github.com/dhedey/02d23e1ff480e355d68713e201c35f50

Thank you!

**Comment by 0xOmarA** [comment]
Hey @chiggimps, thank you for recommending this! This is a feature that I'm currently working on in the [develop](https://github.com/0xOmarA/RadixLib/tree/develop) branch. You can expect to see it in v1.0.1 which I will be releasing soon.

**Comment by 0xOmarA** [comment]
Hey @chiggimps, this has been added in v1.0.1 in the form of the `radix.utils.decode_message` function and its function overrides.
