### ISSUE TITLE
xrd_from_atto and atto_to_xrd could be renamed to "from_atto" and "to_atto" ?

### ISSUE THREAD

**Issue by chiggimps** [0xOmarA/RadixLib#5]
Does every radix token follow that 10**18 atomic amount? 

https://github.com/0xOmarA/RadixLib/blob/2deb1b4657b90b12504f2c5a958492b43ad91248/src/radixlib/derive.py#L205

**Comment by 0xOmarA** [comment]
Hey Chiggimps, at the current moment of time all of the tokens in Radix have a divisibility of 18 meaning that the smallest unit of any token on the Olympia Mainnet is currently 10^-18. 

This changes with Babylon as you've seen in the Scrypto where the developer would be able to specify the divisibility/granularity of their tokens.
